### ISSUE TITLE
Use of the Package

### ISSUE THREAD

**Issue by antgomo** [immunomethylomics/FlowSorted.BloodExtended.EPIC#1]
Hi i installed from the github the package and i tried to use with estimacellCount2 function from previous FlowSorted.BloodEPIC package, but i didn't succeed. Can you help me please? 

Thanks

**Comment by lucassalas** [comment]
@antgomo could you please post your script.
I can help you troubleshoot

**Comment by atomnh** [comment]
Hi,
I installed the package, and try to use it with estimateCellCounts2 function from FlowSorted.BloodEPIC package (v1.99.5) with command as follows but failed. I check the error message, and it seems that FlowSorted.BloodExtended.EPIC is not available through "ExperimentHub".  Could you please help to fix it or tell me what's wrong with my scripts? Many thanks!
library("FlowSorted.Blood.EPIC")
library("FlowSorted.BloodExtended.EPIC")
cellComp_ext<-estimateCellCounts2(RGSet, compositeCellType = "BloodExtended",   
                                processMethod = "preprocessNoob",  
                                probeSelect = "IDOL",  
                                cellTypes = c("CD8T", "CD4T", "NK", "Bcell",  
                                "Mono", "Neu"),  
                                referencePlatform =   
                                "IlluminaHumanMethylationEPIC",  
                                IDOLOptimizedCpGs =IDOLOptimizedCpGsBloodExtended, 
                                referenceset = NULL,  
                                returnAll = TRUE,meanPlot = TRUE, verbose = TRUE)  
And it returns:
R[write to console]: [estimateCellCounts2] Replace 'CD4T' for 'CD4nv', 'CD4mem' and 'Treg' in argument 'cellTypes' for EPIC blood extended estimation.

R[write to console]: [estimateCellCounts2] Replace 'CD8T' for 'CD8nv' and 'CD8mem' in argument 'cellTypes' for EPIC blood extended estimation.

R[write to console]: [estimateCellCounts2] Replace 'Bcell' for 'Bnv' and 'Bmem' in argument 'cellTypes' for EPIC blood extended estimation.

R[write to console]: Error in get(referencePkg) : 
  object 'FlowSorted.BloodExtended.EPIC' not found

**Comment by lucassalas** [comment]
Hi,

Please see the help file for an example https://bioconductor.org/packages/release/data/experiment/vignettes/FlowSorted.Blood.EPIC/inst/doc/FlowSorted.Blood.EPIC.html. The script has changed, also you need to specify the cell types included in the extended deconvolution (all in the example).

Please be aware that the Extended library is not available in Bioconductor, but require a license.

Let me know if you have other issues.

Best,

Lucas

Lucas A Salas, MD MPH PhD
Assistant Professor
Department of Epidemiology
Dartmouth College
Cancer Population Sciences Research Program


On May 26, 2022, at 4:29 PM, atomnh ***@***.***> wrote:

﻿

Hi,
I installed the package, and try to use it with estimateCellCounts2 function from FlowSorted.BloodEPIC package (v1.99.5) with command as follows but failed. I check the error message, and it seems that FlowSorted.BloodExtended.EPIC is not available through "ExperimentHub". Could you please help to fix it or tell me what's wrong with my scripts? Many thanks!
library("FlowSorted.Blood.EPIC")
library("FlowSorted.BloodExtended.EPIC")
cellComp_ext<-estimateCellCounts2(RGSet, compositeCellType = "BloodExtended",
processMethod = "preprocessNoob",
probeSelect = "IDOL",
cellTypes = c("CD8T", "CD4T", "NK", "Bcell",
"Mono", "Neu"),
referencePlatform =
"IlluminaHumanMethylationEPIC",
IDOLOptimizedCpGs =IDOLOptimizedCpGsBloodExtended,
referenceset = NULL,
returnAll = TRUE,meanPlot = TRUE, verbose = TRUE)
And it returns:
R[write to console]: [estimateCellCounts2] Replace 'CD4T' for 'CD4nv', 'CD4mem' and 'Treg' in argument 'cellTypes' for EPIC blood extended estimation.

R[write to console]: [estimateCellCounts2] Replace 'CD8T' for 'CD8nv' and 'CD8mem' in argument 'cellTypes' for EPIC blood extended estimation.

R[write to console]: [estimateCellCounts2] Replace 'Bcell' for 'Bnv' and 'Bmem' in argument 'cellTypes' for EPIC blood extended estimation.

R[write to console]: Error in get(referencePkg) :
object 'FlowSorted.BloodExtended.EPIC' not found

**Comment by atomnh** [comment]
> 

I got the same error again. Even when I try to use the example you provided in the link, same error as follows.
  Error in get(referencePkg) : 
  object 'FlowSorted.BloodExtended.EPIC' not found

**Comment by lucassalas** [comment]
Good morning,

My apologies for the confusion. I thought you had already requested a license and installed it in your system. To be clear, this is an example of an external reference not hosted on Bioconductor.

In the help file, you can see the following message on top.
Blood Extended deconvolution
# Blood Extended deconvolution or any external reference
#please contact ***@***.******@***.***>

# Do not run


For specific instructions, please refer to this website: https://github.com/immunomethylomics/FlowSorted.BloodExtended.EPIC

This license is free for Academic purposes and requires a fee for commercial purposes. Your Technology Transfer Office (or equivalent) needs to sign the document, and once executed, you will have access to the library.

If I am misinterpreting, and you already have the library, let me know to understand the problem. Please also send your session information.

Best,
Lucas A Salas, MD MPH PhD
Assistant Professor
Department of Epidemiology
Dartmouth College
Cancer Population Sciences Research Program
Dartmouth Hitchcock- Norris Cotton Cancer Center
1 Medical Center Dr, DHMC
WTRB 659
Lebanon, NH 03756
(o) 603-646-5496
dartmouth.edu<https://geiselmed.dartmouth.edu/epidemiology/> | Salas Lab<https://sites.dartmouth.edu/salaslab/> | Twitter<https://twitter.com/lsalas_epigenet> | ORCID<https://orcid.org/0000-0002-2279-4097>


On Jun 8, 2022, at 4:03 AM, atomnh ***@***.***> wrote:
﻿

I got the same error again. Even when I try to use the example you provided in the link, same error as follows.
Error in get(referencePkg) :
object 'FlowSorted.BloodExtended.EPIC' not found
