### ISSUE TITLE
failed to access FlowSorted.BloodExtended.EPIC object

### ISSUE THREAD

**Issue by atomnh** [immunomethylomics/FlowSorted.BloodExtended.EPIC#2]
Hi,
I installed the package, and try to use it with estimateCellCounts2 function from FlowSorted.BloodEPIC package (v1.99.5) with command as follows but failed. I check the error message, and it seems that FlowSorted.BloodExtended.EPIC is not available through "ExperimentHub". Could you please help to fix it or tell me what's wrong with my scripts? Many thanks!
library("FlowSorted.Blood.EPIC")
library("FlowSorted.BloodExtended.EPIC")
cellComp_ext<-estimateCellCounts2(RGSet, compositeCellType = "BloodExtended",
processMethod = "preprocessNoob",
probeSelect = "IDOL",
cellTypes = c("CD8T", "CD4T", "NK", "Bcell",
"Mono", "Neu"),
referencePlatform =
"IlluminaHumanMethylationEPIC",
IDOLOptimizedCpGs =IDOLOptimizedCpGsBloodExtended,
referenceset = NULL,
returnAll = TRUE,meanPlot = TRUE, verbose = TRUE)
And it returns:
R[write to console]: [estimateCellCounts2] Replace 'CD4T' for 'CD4nv', 'CD4mem' and 'Treg' in argument 'cellTypes' for EPIC blood extended estimation.

R[write to console]: [estimateCellCounts2] Replace 'CD8T' for 'CD8nv' and 'CD8mem' in argument 'cellTypes' for EPIC blood extended estimation.

R[write to console]: [estimateCellCounts2] Replace 'Bcell' for 'Bnv' and 'Bmem' in argument 'cellTypes' for EPIC blood extended estimation.

R[write to console]: Error in get(referencePkg) :
object 'FlowSorted.BloodExtended.EPIC' not found

**Comment by lucassalas** [comment]
Hi,

Please see the help file for an example https://bioconductor.org/packages/release/data/experiment/vignettes/FlowSorted.Blood.EPIC/inst/doc/FlowSorted.Blood.EPIC.html. The script has changed, also you need to specify the cell types included in the extended deconvolution (all in the example).

Please be aware that the Extended library is not available in Bioconductor, but require a license.

Let me know if you have other issues. The cell types should match those in your reference. If you use the extended library you can only use the 12 cell types specified  int he example for the extended library.
